#!/usr/bin/python
# qpy - user interface to the qpy-multiuser
#
# 31 Dec 2015 - Pradipta and Yuri
from multiprocessing.connection import Client
from time import sleep
import os
import sys
import subprocess
import re
import threading

from qpy_general_variables import *

# Important variables
multiuser_address = 'localhost'
multiuser_key = 'zxcvb'
multiuser_port = 9998

keywords={'nodes':        (MULTIUSER_NODES,      'Reaload nodes file. No arguments'),
          'distribute':   (MULTIUSER_DISTRIBUTE, 'Distribute cores: No arguments'),
          'status' :      (MULTIUSER_STATUS,     'Show status. No arguments'),
          'finish':       (MULTIUSER_FINISH,     'Finish the multiuser execution. No arguments'),
          '__user':       (MULTIUSER_USER,       'Add user. Arguments: user_name'),
          '__req_core':   (MULTIUSER_REQ_CORE,   'Require a core: Arguments: user_name, jobID, n_cores, queue_size'),
          '__remove_job': (MULTIUSER_REMOVE_JOB, 'Remove a job: Arguments: user_name, job_ID, queue_size'),
          }


try:
    option = keywords[sys.argv[1]][0]
except:
    str_len = 0
    for opt in keywords:
        if (keywords[opt][0] < 0):
            continue
        if (str_len < len( opt)):
            str_len = len( opt)
    format_spc = '{0:' + str( str_len+1) + 's}'
    usage_msg =  'Usage: ' + sys.argv[0] +  ' <option> [<arguments>].\n'
    usage_msg += 'Options:'
    for opt in keywords:
        if (keywords[opt][0] < 0):
            continue
        usage_msg += '\n  ' + format_spc.format( opt+':') + ' ' + keywords[opt][1]
    sys.exit( usage_msg)


# Get arguments, according to the option
arguments = ()

# Add user
if (option == MULTIUSER_USER):
    try:
        arguments = (sys.argv[2], [])
    except:
        usage_msg =  'Usage: ' + sys.argv[0] +  ' __user <user_name>.'
        sys.exit( usage_msg)

# Request a core
if (option == MULTIUSER_REQ_CORE):
    try:
        arguments = (sys.argv[2], int(sys.argv[3]), int(sys.argv[4]), int(sys.argv[5]))
    except:
        usage_msg = 'Usage: ' + sys.argv[0] +  ' __req_core <user_name> <jobID> <n_cores> <queue_size>.'
        sys.exit( usage_msg)


# remove a job
if (option == MULTIUSER_REMOVE_JOB):
    try:
        arguments = [sys.argv[2], int( sys.argv[3]), int(sys.argv[4])]
    except:
        usage_msg = 'Usage: ' + sys.argv[0] +  ' __remove_job <user_name> <job_ID> <queue_size>.'
        sys.exit( usage_msg)


class try_connection( threading.Thread):
    def __init__( self):
        threading.Thread.__init__( self)
        self.master = None
    def run( self):
        self.master = Client( (multiuser_address, multiuser_port), authkey=multiuser_key)


M = try_connection()
M.daemon = True
M.start()
n = 0
waiting = 60
while (M.is_alive()):
    n += 1
    if (n == waiting):
        sys.exit( 'Time for connection exceeded. Are you sure that qpy-master is running?')
    sleep( 0.05)

master = M.master
master.send( (option, arguments))
message_back = master.recv()
if (isinstance( message_back[0], tuple)):
    message_back = message_back[0][1]
else:
    message_back = message_back[1]
sys.stdout.write( message_back + '\n')

master.close()
