# qpy - variables used by several files
#
# 11 January 2016 - Pradipta and Yuri

MULTIUSER_NODES          = 1
MULTIUSER_DISTRIBUTE     = 2
MULTIUSER_STATUS         = 3
MULTIUSER_SHOW_VARIABLES = 4
MULTIUSER_FINISH         = 5
MULTIUSER_START          = 6
MULTIUSER_USER           = -1
MULTIUSER_REQ_CORE       = -2
MULTIUSER_REMOVE_JOB     = -3

JOBTYPE_SUB       = 1
JOBTYPE_CHECK     = 2
JOBTYPE_KILL      = 3
JOBTYPE_FINISH    = 4
JOBTYPE_NODES     = 5
JOBTYPE_MAXJOBS   = 6
JOBTYPE_CONFIG    = 7
JOBTYPE_CLEAN     = 8
JOBTYPE_TUTORIAL  = 9
JOBTYPE_STATUS    = 10
JOBTYPE_RESTART   = 11
JOBTYPE_CTRLQUEUE = 12
JOBTYPE_NOTE      = 13
